config/routes.rb
StyleLust::Application.routes.draw do

  get "/about" => "items#about", as: :about
  get "items/likedItems" => "items#likedItems", as: :likedItems
  get "sessions/create"
  get "sessions/destroy"
  get "/apis/index" => "apis#index", as: :api
  get "/apis/updater" => "apis#updater", as: :updater
  match 'auth/:provider/callback', to: 'sessions#create', as: 'signin', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :items
  resources :likes
  resources :users
  resources :auths, only:[:create,:new,:index]
  get '/hotPicks' => 'items#hotPicks', as: :hotPicks

  root 'items#welcome'

end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController

	def new
		if current_user
			redirect_to items_path
		else
			@user = User.new
			
		end
	end


	def create
		#pull the user from mongo
			@user = User.where(email: params[:user][:email]) 
				#check to see if the user exists and the password matches
				if @user.length > 0 && @user[0].authenticated?(params[:user][:password])
					flash[:notice] = "Logged in"
					#store the session
					session[:user_id] = @user[0].id
					redirect_to root_path
				else
					flash[:notice] = "Incorrect Login Info"
					redirect_to root_path
				end
	end

end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/views/auths/_login.html.erb
<div id="loginModal" class="reveal-modal" data-reveal>

	<a class="close-reveal-modal">&#215;</a>

	<h1 id="loginHeader">Log In</h1>

	<div class="login">
		<%= form_for :user, {url: auths_path, method: 'post'} do |f| %>

		  <%= f.label :email %>
	    <%= f.text_field :email, :placeholder => "Email Address" %><br />
	    <%= f.label :password %>
	    <%= f.password_field :password, :placeholder => "Enter password" %><br />
	    <%= f.submit 'Login', class: "button fave-buy-btn"  %>
	  <% end %>
	</div>

</div>

app/views/auths/create.html.erb
<h1>Auths#create</h1>
<p>Find me in app/views/auths/create.html.erb</p>

app/views/auths/new.html.erb
<div class="login-mobile">
	<h1 id="logo">Log In</h1>

  <%= form_for @user, {url: auths_path } do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %><br />
    <%= f.label :password %>
    <%= f.password_field :password %><br />
    <%= f.submit 'Login', class: "button fave-buy-btn"  %>
  <% end %>
</div>