config/routes.rb
StyleLust::Application.routes.draw do

  get "/about" => "items#about", as: :about
  get "items/likedItems" => "items#likedItems", as: :likedItems
  get "sessions/create"
  get "sessions/destroy"
  get "/apis/index" => "apis#index", as: :api
  get "/apis/updater" => "apis#updater", as: :updater
  match 'auth/:provider/callback', to: 'sessions#create', as: 'signin', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :items
  resources :likes
  resources :users
  resources :auths, only:[:create,:new,:index]
  get '/hotPicks' => 'items#hotPicks', as: :hotPicks

  root 'items#welcome'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :brand
  has_many :likes
  has_many :users, through: :likes
  validates :name, presence: {message: "name must be present"}
  validates :price, presence: {message: "price must be present"}
  #validates :category_id, presence: {message: "category_id must be present"}
  #validates :brand_id, presence: {message: "brand_id must be present"}
  validates :photo, presence: {message: "photo must be present"}
  validates :click_url, presence: {message: "click_url must be present"}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

		
	def index
		
		respond_to do |format|
			format.json { 
 				get_hot_picks(3)
 			}
	      format.html {
					@items = limit_items
		    }
	    end
	end


	def create 
		@items = limit_items
		if params[:is_like] == "true"
			likeClicked()
		elsif params[:is_like] == "false"
			dislikeClicked()
		else
			#this is where we will add new items with an api request
			render action: 'index'
		end
		
	end


	def likeClicked
		Like.create(user_id: current_user.id, item_id: @items.first.id, is_like: true)
		@items.shift
		render action: 'index'
	end

	def dislikeClicked
		Like.create(user_id: current_user.id, item_id: @items.first.id, is_like: false)
		@items.shift
		render action: 'index'
	end

	def likedItems
		
	end

	def about
		render file: 'app/views/layouts/about.html.erb'
	end

	def hotPicks
		get_hot_picks(20)
	end

private

	def limit_items
		
		@items = Item.all
		@items = @items.joins(:category).where(categories: {name: params[:cat]}) if params[:cat]
		@items = @items.where("items.price < ?", params[:price]) if params[:price]
		
		@items = @items.where.not(id: Item.joins(:likes).where(likes: {user_id: current_user.id}).pluck(:id))
		return @items.to_a

	end


	def get_hot_picks(how_many)
		@items = Item.find_by_sql("SELECT i.id, i.name, i.price, i.category_id, i.brand_id, i.photo, i.click_url, COUNT(l.item_id) FROM items AS i LEFT OUTER JOIN likes AS l ON i.id = l.item_id WHERE l.is_like = 't' GROUP BY i.id, i.name, i.price, i.category_id, i.brand_id, i.photo, i.click_url ORDER BY COUNT(l.item_id) DESC LIMIT "+ how_many.to_s + ";") 
		
	end

	

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_modal.html.erb
<div id="myModal" class="reveal-modal" data-reveal>
	<a class="close-reveal-modal">&#215;</a>
  <iframe class="iframe" src="<%= @items.first.click_url %>"> </iframe>
  
</div>

app/views/items/_shopsettings.html.erb
<!-- budget slider -->
<p>
  <label for="amount">Budget:</label>
  <input type="text" id="amount" style="border:0; color:#99A5BE; font-weight:bold;">
</p>

<div id="slider2"></div>

<br>

<!-- category dropdown -->
<label for="category">Category:</label>
<br>
<div class="large-12 small-12 columns">

<select class="fancy-select" id="first_drop">
  <option value="">Select</option>
  <%= options_for_select([['Tops', 1], ['Bottoms', 2], ['Dresses', 3], ['Outerwear', 4], ['Accessories', 5], ['Shoes', 6]], 1) %>
</select>

<br>

<!-- apply settings button -->
<div id="a">
  <div class="large-12 small-12 columns">
    <div onclick="buildUrl()" class="button" id="save">APPLY</div> 
  </div>
</div>


<script>
  $(function(){

    // budget slider
    $( "#slider2" ).slider({
      value:100,
      min: 20,
      max: 5000,
      step: 20,
      animate: true,
      slide: function( event, ui ) {
        $( "#amount" ).val( "$" + ui.value );
        // console.log(ui.value);
      }
    });
    $( "#amount" ).val( "$" + $( "#slider2" ).slider( "value" ) );
    


    $('.fancy-select').fancySelect();
  });

  function buildUrl(){
    var val = $( "#slider2" ).slider( "value" ) 

    var url = "http://stylelust.herokuapp.com/items?cat=" + $('#first_drop option:selected').text() + "&price=" + val;

    // var url = window.location.protocol + '//' + window.location.host + "/items?cat=" + $('#first_drop option:selected').text() + "&price=" + val;
    
    console.log(url);

    window.location.href = url;
    $('#panel1').removeClass("active");
    console.log(url);
  };

</script>

app/views/items/hotPicks.html.erb
<h1 class="play">HOT PICKS</h1>

<div class="row" id="hotpicks"></div>

  <script id="hotpicks-template" type="text/x-handlebars-template">
    {{#each hotpicks}}
    <a href="{{click_url}}">
    <div class="large-4 columns favorites">
     
      <ul class="pricing-table test">
     
        <li class="title product-name">{{name}}</li>
        <li class="price uniform"><img src='{{image_url}}' /></li>
        <li class="price uniform bullet-item">${{price}}.00</li>
       <a href="{{click_url}}" class="button fave-buy-btn">
       <li class="cta-button"></li></a> 
     
      </ul>
    </div>
      </a>
       {{/each}}
  
  </script>

  <script type="text/javascript">
  $(function() {
    loadHotPicks20();
  });
</script>




<!--  <h1>Hot Picks</h1>
<div class="row" id="hotpicks"></div>

<script id="hotpicks-template" type="text/x-handlebars-template">
  {{#each hotpicks}}
    <a href="{{click_url}}">
      <div class="large-4 columns hotnow">
        <img src="{{image_url}}" />
        <h5>{{name}}</h5>
      </div>
    </a>
  {{/each}}
</script>
<script type="text/javascript">
  $(function() {
    loadHotPicks20();
  });
</script> -->

app/views/items/index.html.erb
<h1 class="play"><%= @items.first.category.name.upcase %></h1>
 <div class="row" id="swipe">
 		<div class="deckcontainer expandOpen large-12 small-12 columns">

	    <div class="itemdeck expandOpen">
        <%= link_to image_tag(@items.first.photo) , '#myModal', 'data-reveal-id'=> "myModal", class: "show-for-medium-up"%> 
        <%= link_to image_tag(@items.first.photo) , @items.first.click_url, class: "show-for-small-only"%> 
	      <br>
	    </div>

	    <div class="product-details">
	    	<%= @items.first.name %>
	    	<br>
        <%= number_to_currency(@items.first.price) %>
      </div>

	  </div>

    <div class="shopbar">
        <%= link_to "LOSE", items_path(cat: params[:cat], price: params[:price], is_like: false), class: "button lose slideOutLeft", method: 'post' %>

  		<div class="show-for-small-only">
        <%= link_to "BUY",@items.first.click_url,class: "button buy" %>
      </div>

  		<div class="show-for-medium-up">
  			<%= link_to "BUY", '#myModal', 'data-reveal-id'=> "myModal", class: "button buy" %>
  		</div> 
  		
        <%= link_to "LUST", items_path(cat: params[:cat], price: params[:price], is_like: true), class: "button lust slideOutRight", method: 'post' %>
    </div>
    
		 <%=render partial:'items/modal' %>

  </div>

<script>
$(function() {      
      //Enable swiping...
      $("#swipe").swipe( {
        //Generic swipe handler for all directions
        swipeLeft:function(event, direction, distance, duration, fingerCount) {
          console.log("You swiped " + direction );  
          $.post('<%= items_path(cat: params[:cat], price: params[:price], is_like: false) %>', function(response) {
            location.href = location.href;
          });
        },
        swipeRight:function(event, direction, distance, duration, fingerCount) {
          console.log("You swiped " + direction );  
          $.post('<%= items_path(cat: params[:cat], price: params[:price], is_like: true) %>', function(response) {
            location.href = location.href;
          });
        },
        //Default is 75px, set to 0 for demo so any distance triggers swipe
         threshold:50
      });
    });

      $(function(){
        $(".slideOutLeft").click(function(){
          $(".itemdeck").toggleClass("itemdeck-left");
        });
      });

      $(function(){
        $(".slideOutRight").click(function(){
          $(".itemdeck").toggleClass("itemdeck-right");
        });
      });

    

</script>

app/views/items/likedItems.html.erb
<h1 class="play">FAVORITES</h1>

<div class="row">
  <% current_user.liked_items.each do |item| %>
    <div class="large-4 columns favorites">
      <ul class="pricing-table test">
        <li class="title product-name"><%= item.name %></li>
        <li class="price uniform"><%= link_to image_tag(item.photo), '#myModal' + item.id.to_s, 'data-reveal-id'=> ("myModal" + item.id.to_s) %></li>
        <li class="bullet-item"><%= number_to_currency(item.price) %></li>
        <li class="cta-button"><%= link_to "BUY",'#myModal' + item.id.to_s, 'data-reveal-id'=> ("myModal" + item.id.to_s), class: "button fave-buy-btn" %></li>
      </ul>
    </div>
    <div id="myModal<%= item.id %>" class="reveal-modal myModal" data-reveal>
      <a class="close-reveal-modal">&#215;</a>
      <iframe class="iframe" src="<%= item.click_url.to_s %>"> </iframe>
      
    </div>
  <% end %>
</div>

app/views/items/welcome.html.erb
<!-- Header -->
<div class="show-for-medium-up">
  <div class="row">
    <div class="large-3 columns">
      <h1 id="logo">STYLELUST</h1>
    </div>
  </div>
</div>  


<h1 class="show-for-small-only" id="logo-small">STYLELUST</h1>
<!-- End Header -->
 
<!-- First Band (Weekend Update) -->

<div id="front-image"></div>


<!-- Three-up Content Blocks -->
<div class="parallax-wrapper">
  <div class="row">

    <div class="large-4 columns">
      <div class="icon-info" data-tooltip data-options="disable_for_touch:true" title= "Discover new fashion styles and trends from the hottest brands.">
        <%= image_tag("discover.svg", class: "front-icons expandOpen") %>
      </div>
        <h4>Discover</h4>
    </div>

    <div class="large-4 columns">
      <div class="icon-info" data-tooltip data-options="disable_for_touch:true" title= "Share your lookbooks with your friends on Facebook or Instagram.">
        <%= image_tag("share.svg", class: "front-icons expandOpen") %>
      </div>
        <h4>Share</h4>
    </div>

    <div class="large-4 columns">
      <div class="icon-info" data-tooltip data-options="disable_for_touch:true" title= "Buy your favorite items from hundreds of brands in one location.">
        <%= image_tag("shop.svg", class: "front-icons expandOpen") %>
      </div>
        <h4>Shop</h4>
    </div>
    
  </div>

  <hr id="cta" />
  <% if current_user %>
              
    <%= link_to items_path do %>
  <div id="explore">EXPLORE NOW</div><% end %>
  <% else %>
    <%= link_to new_auth_path do %>
  <div id="explore">EXPLORE NOW</div><% end %>
  <% end %>


<!-- Hot Now -->
  <h1 id="logo">HOT NOW</h1>
  <div class="row" id="hotnow"></div>

  <%=link_to hotPicks_path do %>
  <div id="hotbutton">SEE MORE &nbsp; &#62;</div>
  <%end%>


<!-- Brands -->
  <div class="row brands">
    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/burberry.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/freepeople.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/gucci.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/jeffreycampbell.png") %>
    </div>
  </div>

  <div class="row">
    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/louboutin.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/louisvuitton.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/nars.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/nastygal.png") %>
    </div>
  </div>

  <div class="row">
    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/nike.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/opi.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/samedelman.png") %>
    </div>

    <div class="large-3 medium-3 small-3 columns">
      <%= image_tag("logo/urbanoutfitters.png") %>
    </div>
  </div>
    
</div>

<script id="hotnow-template" type="text/x-handlebars-template">
  {{#each items}}
    <a href="{{click_url}}">
      <div class="large-12 columns hotnow">
        <img src="{{image_url}}" class="desaturate" />
        <h5>{{name}}</h5>
      </div>
    </a>
  {{/each}}
</script>
<script type="text/javascript">
  $(function() {
    loadHotPicks3();
  



  $(window).bind('scroll',function(e){
      parallaxScroll();
  });
 
  function parallaxScroll(){
    var scrolled = $(window).scrollTop();

    $('.parallax-wrapper').css('top',(4-(scrolled*.9))+'px');
  }
});
</script>