config/routes.rb
StyleLust::Application.routes.draw do

  get "/about" => "items#about", as: :about
  get "items/likedItems" => "items#likedItems", as: :likedItems
  get "sessions/create"
  get "sessions/destroy"
  get "/apis/index" => "apis#index", as: :api
  get "/apis/updater" => "apis#updater", as: :updater
  match 'auth/:provider/callback', to: 'sessions#create', as: 'signin', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :items
  resources :likes
  resources :users
  resources :auths, only:[:create,:new,:index]
  get '/hotPicks' => 'items#hotPicks', as: :hotPicks

  root 'items#welcome'

end

app/views/layouts/_nav.html.erb
<div class="page">

<div class="off-canvas-wrap">
  <div class="inner-wrap">
    <div class="fixed">
    <nav class="tab-bar">

      <!-- Hamburger Menu Icon for Left Menu Toggle -->
      <section class="left-small">
        <%= image_tag("menu.png", class: "menu left-off-canvas-toggle" ) %>
      </section>

      <!-- Brand Name on Nav - Leads to Homepage -->
      <section class="middle tab-bar-section">
        <%= link_to root_path do %>
          <h1 class="title">StyleLust</h1>
        <% end %>
      </section>     
    
      <!-- User Icon for Right Menu Toggle -->
    <section class="right-small">
          <%= image_tag("user.svg", class: "user right-off-canvas-toggle") %>
      </section>
    </nav>
  </div>

    <!-- Right Menu (User Panel) -->
    <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
      	<% if current_user %>
      	<li><a><% if !!current_user.image %><%= image_tag current_user.image, size: '80' %><% end %></a></li>
      	<li><a><%= current_user.first_name %> </a></li>
      	<li><a><%= current_user.email %></a></li>
      	<li><%= link_to "Logout", signout_path, id: "sign_out" %></a></li>
      	<% else %>
        <li><label>StyleLust</label></li>
      	<li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "#sign_in" %></li>
      	<li class="show-for-small-only"><%= link_to "Sign In", new_auth_path %></li>
        <li class="show-for-medium-up"><%= link_to "Sign In", "#loginModal", 'data-reveal-id' => "loginModal" %></li>
      	<li class="show-for-small-only"><%= link_to "Sign Up", new_user_path %></li>
        <li class="show-for-medium-up"><%= link_to "Sign Up", "#signupModal", 'data-reveal-id' => "signupModal" %></li>
        <% end %>
      </ul>
    </aside>

    <!-- Left Menu (Links to All App Views) -->
    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>StyleLust</label></li>
        <% if current_user %>

        <li><%= link_to root_path do %>Home</li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><a href="http://stylelust.herokuapp.com/hotPicks.json">API</a></li>
        <li><%= link_to hotPicks_path do %>Hot Picks</li>
        <% end %>
        <li><%= link_to likedItems_path do %>Favorites</li>
        <% end %>
      
        <li>
          <dl class="accordion" data-accordion>
            <dd>
              <a href="#panel1" id="settings">Shop</a>
              <div id="panel1" class="content">

                  <%= render partial: 'items/shopsettings' %>

                </div>
            </dd>
          </dl>

        </li>

        <% else %>
        <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "#sign_in" %></li>
        <li class="show-for-small-only"><%= link_to "Sign In", new_auth_path %></li>
        <li class="show-for-medium-up"><%= link_to "Sign In", "#loginModal", 'data-reveal-id' => "loginModal" %></li>
        <li class="show-for-small-only"><%= link_to "Sign Up", new_user_path %></li>
        <li class="show-for-medium-up"><%= link_to "Sign Up", "#signupModal", 'data-reveal-id' => "signupModal" %></li>
        <% end %>
      </ul>

      <%=render partial:'auths/login' %>
      <%=render partial:'users/signup', controller: 'auths', action: 'new' %>
    </aside>

    <!-- Main Content Section Where Each Page is Shown -->
    <section class="main-section">


      <%= yield %>


    </section>

  <a class="exit-off-canvas"></a>

  
    <!-- Footer -->
  
    <footer class="row">
      <div class="large-12 columns">
        <hr />
        <div class="row">
          <div class="large-6 columns">
            <p class="footer">© 2014 StyleLust. All Rights Reserved.</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><%= link_to "About", about_path, class: "footer" %></li>
              <li><a href="http://stylelust.herokuapp.com/hotPicks.json" class="footer">API</a></li>
              <li><%= link_to "Contact", about_path, class: "footer" %></li>
            </ul>
          </div>
        </div>
      </div> 
    </footer>

  </div>
</div>

</div>
  

app/views/layouts/about.html.erb
<h1 id="developedBy">CREATED BY:</h1>

<%= image_tag("team_EAK.gif", id: "gif") %>

<div class="row about">
	<div class="large-4 small-4 columns">			
			<a href="http://www.linkedin.com/pub/elena-hoshizaki/38/2b4/19" target="_blank"><%= image_tag("ellie.svg", class: "EAK") %></a>
	</div>
	<div class="large-4 small-4 columns">
		<h4><a href="http://www.linkedin.com/pub/kendrick-parks/53/8bb/317" target="_blank"> <%= image_tag("kendrick.svg", class: "EAK") %> </a></h4>
	</div>
	<div class="large-4 small-4 columns">
		<h4><a href="http://www.linkedin.com/in/estradaalexandra" target="_blank"><%= image_tag("alex.svg", class: "EAK") %></a></h4>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "StyleLust" %></title>

    <%= stylesheet_link_tag    "application" %>
    
    <%= javascript_include_tag "vendor/modernizr" %> 
    
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>

    <%#= yield %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "foundation" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>